name: CI

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: Sumit-Runner

    steps:
      - name: CheckOut-Code 
        uses: actions/checkout@v4

      - name: Nodejs-Setup
        uses: actions/setup-node@v4
        with:
          node-version: 18 
          cache: 'npm'
          cache-dependency-path: ReactTodoUIMonolith/package-lock.json

      - name: Install dependencies
        working-directory: ReactTodoUIMonolith
        run: npm ci                

      - name: Build
        working-directory: ReactTodoUIMonolith
        run: npm run build

      - name: Test
        working-directory: ReactTodoUIMonolith
        run: npm test --if-present

